function jac = get_jacobian(theta, phi)
    jac = 3*sin(theta)^4 * sin(phi)^2 + 2*sin(theta)^4 * cos(phi)^2 + 12*sin(theta)^2 * ...
        cos(theta)^2 * sin(phi)^2 * cos(phi)^2 + 6*sin(theta)^2 * cos(theta)^2 * sin(phi)^4 + ...
        6*sin(theta)^2 * cos(theta)^2 * cos(phi)^4;
end
